apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    chart-use: once
    app: "{{ .Chart.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    app: "{{  .Chart.Name }}"
